# Generated by Django 3.1.3 on 2021-01-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BooksGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='books.bookssection')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('book_cover', models.ImageField(blank=True, upload_to='books/%Y/%m/%d')),
                ('number_of_pages', models.IntegerField()),
                ('year_publishing', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('retelling', models.TextField(blank=True)),
                ('quotes', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=250)),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.booksgenre')),
                ('list_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.bookssection')),
            ],
            options={
                'ordering': ('-date_pub',),
            },
        ),
    ]
