# Generated by Django 3.1.3 on 2021-01-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210109_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
