# Generated by Django 3.1.3 on 2021-01-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture_for_wall', models.ImageField(upload_to='wall_of_heroes/%Y/%m/%d')),
                ('picture_for_detail', models.ImageField(blank=True, upload_to='wall_of_heroes/%Y/%m/%d')),
                ('short_biography', models.TextField()),
                ('influenced_me', models.TextField()),
                ('quotes', models.TextField()),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
