# Generated by Django 3.1.3 on 2021-01-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20210110_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_reg',
        ),
    ]
